{"name": "Вход курьера с неверными учетными данными - пароль", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидался код состояния 400, но был получен 404. Ответ: {\"code\":404,\"message\":\"Not Found.\"}\nassert 404 == 400\n +  where 404 = <Response [404]>.status_code", "trace": "self = <tests.test_courier_login.TestCourierLogin object at 0x000001B6771173D0>\n\n    @allure.title(\"Вход курьера с неверными учетными данными - пароль\")\n    def test_authorization_with_password_is_invalid(self):\n        response = login_courier(TestDataLogin.valid_login_and_invalid_login)\n>       assert response.status_code == 400, f\"Ожидался код состояния 400, но был получен {response.status_code}. Ответ: {response.text}\"\nE       AssertionError: Ожидался код состояния 400, но был получен 404. Ответ: {\"code\":404,\"message\":\"Not Found.\"}\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\test_courier_login.py:22: AssertionError"}, "steps": [{"name": "Вход курьера в систему", "status": "passed", "parameters": [{"name": "credentials", "value": "{'login': 'Petrov', 'password': '[12345]'}"}], "start": 1704721380656, "stop": 1704721381037}], "start": 1704721380656, "stop": 1704721381039, "uuid": "603867c9-7b74-4bd0-8410-daf9617de311", "historyId": "c6ade77bcb44ff981bafd2c99dd539eb", "testCaseId": "c6ade77bcb44ff981bafd2c99dd539eb", "fullName": "tests.test_courier_login.TestCourierLogin#test_authorization_with_password_is_invalid", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "LAPTOP-1KK7H688"}, {"name": "thread", "value": "10096-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}