{"name": "Вход курьера с неверными учетными данными", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 401\n +  where 404 = <Response [404]>.status_code", "trace": "@allure.title(\"Вход курьера с неверными учетными данными\")\n    def test_invalid_courier_login():\n        response = login_courier({\"login\": \"nonexistent\", \"password\": \"invalid\"})\n>       assert response.status_code == 401  # Предполагаем, что 401 - корректный код ошибки для неверного входа\nE       assert 404 == 401\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\test_courier_login.py:16: AssertionError"}, "start": 1703686141683, "stop": 1703686142148, "uuid": "9d81ea87-eb27-42f8-a9ff-a06e060828ac", "historyId": "12a7be10c021dfef5066c145afae2d23", "testCaseId": "12a7be10c021dfef5066c145afae2d23", "fullName": "tests.test_courier_login#test_invalid_courier_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "host", "value": "LAPTOP-1KK7H688"}, {"name": "thread", "value": "13980-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}