{"name": "Вход курьера с неверными учетными данными - логин", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидался код состояния 400, но был получен 404. Ответ: {\"code\":404,\"message\":\"Not Found.\"}\nassert 404 == 400\n +  where 404 = <Response [404]>.status_code", "trace": "self = <tests.test_courier_login.TestCourierLogin object at 0x000001B676E17D50>\n\n    @allure.title(\"Вход курьера с неверными учетными данными - логин\")\n    def test_authorization_with_login_is_invalid(self):\n        response = login_courier(TestDataLogin.invalid_login_and_password)\n>       assert response.status_code == 400, f\"Ожидался код состояния 400, но был получен {response.status_code}. Ответ: {response.text}\"\nE       AssertionError: Ожидался код состояния 400, но был получен 404. Ответ: {\"code\":404,\"message\":\"Not Found.\"}\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\test_courier_login.py:16: AssertionError"}, "steps": [{"name": "Вход курьера в систему", "status": "passed", "parameters": [{"name": "credentials", "value": "{'login': [12345], 'password': '12345'}"}], "start": 1704721380315, "stop": 1704721380655}], "start": 1704721380315, "stop": 1704721380655, "uuid": "3cad0a5e-9d6b-43b5-8c3d-fe6404708442", "historyId": "e2bfddee8da026233d3b4258901cc03e", "testCaseId": "e2bfddee8da026233d3b4258901cc03e", "fullName": "tests.test_courier_login.TestCourierLogin#test_authorization_with_login_is_invalid", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "LAPTOP-1KK7H688"}, {"name": "thread", "value": "10096-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}