{"uid":"45ff5a2da04e951","name":"Вход курьера с неверными учетными данными - логин","fullName":"tests.test_courier_login.TestCourierLogin#test_authorization_with_login_is_invalid","historyId":"e2bfddee8da026233d3b4258901cc03e","time":{"start":1704721380315,"stop":1704721380655,"duration":340},"status":"failed","statusMessage":"AssertionError: Ожидался код состояния 400, но был получен 404. Ответ: {\"code\":404,\"message\":\"Not Found.\"}\nassert 404 == 400\n +  where 404 = <Response [404]>.status_code","statusTrace":"self = <tests.test_courier_login.TestCourierLogin object at 0x000001B676E17D50>\n\n    @allure.title(\"Вход курьера с неверными учетными данными - логин\")\n    def test_authorization_with_login_is_invalid(self):\n        response = login_courier(TestDataLogin.invalid_login_and_password)\n>       assert response.status_code == 400, f\"Ожидался код состояния 400, но был получен {response.status_code}. Ответ: {response.text}\"\nE       AssertionError: Ожидался код состояния 400, но был получен 404. Ответ: {\"code\":404,\"message\":\"Not Found.\"}\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\test_courier_login.py:16: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"AssertionError: Ожидался код состояния 400, но был получен 404. Ответ: {\"code\":404,\"message\":\"Not Found.\"}\nassert 404 == 400\n +  where 404 = <Response [404]>.status_code","statusTrace":"self = <tests.test_courier_login.TestCourierLogin object at 0x000001B676E17D50>\n\n    @allure.title(\"Вход курьера с неверными учетными данными - логин\")\n    def test_authorization_with_login_is_invalid(self):\n        response = login_courier(TestDataLogin.invalid_login_and_password)\n>       assert response.status_code == 400, f\"Ожидался код состояния 400, но был получен {response.status_code}. Ответ: {response.text}\"\nE       AssertionError: Ожидался код состояния 400, но был получен 404. Ответ: {\"code\":404,\"message\":\"Not Found.\"}\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\test_courier_login.py:16: AssertionError","steps":[{"name":"Вход курьера в систему","time":{"start":1704721380315,"stop":1704721380655,"duration":340},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"credentials","value":"{'login': [12345], 'password': '12345'}"}],"hasContent":true,"attachmentStep":false,"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0}],"attachments":[],"parameters":[],"hasContent":true,"attachmentStep":false,"stepsCount":1,"shouldDisplayMessage":true,"attachmentsCount":0},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_courier_login"},{"name":"subSuite","value":"TestCourierLogin"},{"name":"host","value":"LAPTOP-1KK7H688"},{"name":"thread","value":"10096-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_courier_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"45ff5a2da04e951.json","parameterValues":[]}