{"uid":"93ffdfc919b492f9","name":"Вход курьера с неверными учетными данными - пароль","fullName":"tests.test_courier_login.TestCourierLogin#test_authorization_with_password_is_invalid","historyId":"c6ade77bcb44ff981bafd2c99dd539eb","time":{"start":1704721380656,"stop":1704721381039,"duration":383},"status":"failed","statusMessage":"AssertionError: Ожидался код состояния 400, но был получен 404. Ответ: {\"code\":404,\"message\":\"Not Found.\"}\nassert 404 == 400\n +  where 404 = <Response [404]>.status_code","statusTrace":"self = <tests.test_courier_login.TestCourierLogin object at 0x000001B6771173D0>\n\n    @allure.title(\"Вход курьера с неверными учетными данными - пароль\")\n    def test_authorization_with_password_is_invalid(self):\n        response = login_courier(TestDataLogin.valid_login_and_invalid_login)\n>       assert response.status_code == 400, f\"Ожидался код состояния 400, но был получен {response.status_code}. Ответ: {response.text}\"\nE       AssertionError: Ожидался код состояния 400, но был получен 404. Ответ: {\"code\":404,\"message\":\"Not Found.\"}\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\test_courier_login.py:22: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"AssertionError: Ожидался код состояния 400, но был получен 404. Ответ: {\"code\":404,\"message\":\"Not Found.\"}\nassert 404 == 400\n +  where 404 = <Response [404]>.status_code","statusTrace":"self = <tests.test_courier_login.TestCourierLogin object at 0x000001B6771173D0>\n\n    @allure.title(\"Вход курьера с неверными учетными данными - пароль\")\n    def test_authorization_with_password_is_invalid(self):\n        response = login_courier(TestDataLogin.valid_login_and_invalid_login)\n>       assert response.status_code == 400, f\"Ожидался код состояния 400, но был получен {response.status_code}. Ответ: {response.text}\"\nE       AssertionError: Ожидался код состояния 400, но был получен 404. Ответ: {\"code\":404,\"message\":\"Not Found.\"}\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\test_courier_login.py:22: AssertionError","steps":[{"name":"Вход курьера в систему","time":{"start":1704721380656,"stop":1704721381037,"duration":381},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"credentials","value":"{'login': 'Petrov', 'password': '[12345]'}"}],"hasContent":true,"attachmentStep":false,"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0}],"attachments":[],"parameters":[],"hasContent":true,"attachmentStep":false,"stepsCount":1,"shouldDisplayMessage":true,"attachmentsCount":0},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_courier_login"},{"name":"subSuite","value":"TestCourierLogin"},{"name":"host","value":"LAPTOP-1KK7H688"},{"name":"thread","value":"10096-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_courier_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"93ffdfc919b492f9.json","parameterValues":[]}